export default {
  appName: 'PM-LLM Project Manager',
  sidebar: { projects: 'Projects', dashboard: 'Dashboard', tasks: 'Tasks', users: 'User Management', gantt: 'Gantt Chart', pert: 'PERT Chart', criticalPath: 'Critical Path', import: 'Import xlsx', export: 'Export' },
  common: { save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', add: 'Add', search: 'Search', confirm: 'Confirm', loading: 'Loading...', noData: 'No data', required: 'Required', submit: 'Submit', close: 'Close', status: 'Status', actions: 'Actions', name: 'Name', langSwitch: '繁體中文' },
  project: { title: 'Project Overview', name: 'Project Name', startDate: 'Start Date', endDate: 'End Date', duration: 'Duration (days)', progress: 'Progress', status: 'Status', statusPlanned: 'Planned', statusInProgress: 'In Progress', statusCompleted: 'Completed', statusOnHold: 'On Hold', newProject: 'New Project', editProject: 'Edit Project', switchProject: 'Switch Project', deleteConfirm: 'Delete this project?', selectProject: 'Select Project', currentProject: 'Current Project', saveSuccess: 'Project saved', createSuccess: 'Project created' },
  task: { title: 'Task List', name: 'Task Name', description: 'Description', assignee: 'Assignee', startDate: 'Start Date', endDate: 'End Date', duration: 'Duration (days)', progress: 'Progress %', status: 'Status', statusNotStarted: 'Not Started', statusInProgress: 'In Progress', statusCompleted: 'Completed', statusBlocked: 'Blocked', predecessors: 'Predecessors', addPredecessor: 'Add Predecessor', noPredecessors: 'No Predecessors', type: 'Type', isMilestone: 'Milestone', requiredField: 'Task name is required', deleteConfirm: 'Delete this task?', addSuccess: 'Task added', editSuccess: 'Task updated', deleteSuccess: 'Task deleted' },
  user: { title: 'User Management', name: 'Username', email: 'Email', role: 'Role', roles: { admin: 'Admin', manager: 'Manager', member: 'Member', viewer: 'Viewer' }, addUser: 'Add User', editUser: 'Edit User', deleteConfirm: 'Delete this user?' },
  gantt: { title: 'Gantt Chart', zoomIn: 'Zoom In', zoomOut: 'Zoom Out', today: 'Today', tasks: 'Tasks', milestone: 'Milestone', criticalPath: 'Critical Path', criticalPathLabel: 'Critical Path Task', week: 'Week', month: 'Month' },
  pert: { title: 'PERT Chart', criticalPath: 'Critical Path', earlyStart: 'Early Start', earlyFinish: 'Early Finish', lateStart: 'Late Start', lateFinish: 'Late Finish', floatTime: 'Float', duration: 'Duration', task: 'Task', milestone: 'Milestone', legend: 'Legend', normalTask: 'Normal Task', criticalTask: 'Critical Task' },
  criticalPath: { title: 'Critical Path Analysis', pathTasks: 'Critical Path Tasks', totalDuration: 'Total Duration', floatTime: 'Float Time', critical: 'Critical', nonCritical: 'Non-Critical', description: 'The Critical Path is the longest sequence of tasks that determines the minimum project completion time. Any delay on the critical path directly impacts the project finish date.', lag: 'Lag', tolerance: 'Tolerance' },
  dashboard: { title: 'Dashboard', totalTasks: 'Total Tasks', completedTasks: 'Completed', inProgressTasks: 'In Progress', overdueTasks: 'Overdue', totalUsers: 'Users', projectProgress: 'Project Progress', upcomingMilestones: 'Upcoming Milestones', teamWorkload: 'Team Workload', criticalPathInfo: 'Critical Path Info' },
};
